{
    "language": "english",
    "concepts": [
        {
            "text": "Amgen",
            "dbpedia": "http://dbpedia.org/resource/Amgen",
            "freebase": "http://rdf.freebase.com/ns/m.03r820",
            "website": "http://www.amgen.com",
            "crunchbase": "http://www.crunchbase.com/company/amgen",
            "yago": "http://yago-knowledge.org/resource/Amgen",
            "relevance": "0.978435",
            "opencyc": "http://sw.opencyc.org/concept/Mx4rvitPfpwpEbGdrcN5Y29ycA"
        },
        {
            "text": "Etanercept",
            "yago": "http://yago-knowledge.org/resource/Etanercept",
            "relevance": "0.457063",
            "freebase": "http://rdf.freebase.com/ns/m.036lyn",
            "dbpedia": "http://dbpedia.org/resource/Etanercept"
        },
        {
            "text": "Filgrastim",
            "yago": "http://yago-knowledge.org/resource/Filgrastim",
            "relevance": "0.434701",
            "freebase": "http://rdf.freebase.com/ns/m.02qg5g",
            "dbpedia": "http://dbpedia.org/resource/Filgrastim"
        },
        {
            "text": "Osteoporosis",
            "relevance": "0.403637",
            "freebase": "http://rdf.freebase.com/ns/m.05mdx",
            "dbpedia": "http://dbpedia.org/resource/Osteoporosis"
        },
        {
            "opencyc": "http://sw.opencyc.org/concept/Mx4rwP1YbJwpEbGdrcN5Y29ycA",
            "text": "Oncology",
            "relevance": "0.398445",
            "freebase": "http://rdf.freebase.com/ns/m.0hl17",
            "dbpedia": "http://dbpedia.org/resource/Oncology"
        },
        {
            "opencyc": "http://sw.opencyc.org/concept/Mx4rvw_UD5wpEbGdrcN5Y29ycA",
            "text": "Rheumatoid arthritis",
            "relevance": "0.379962",
            "freebase": "http://rdf.freebase.com/ns/m.06g7c",
            "dbpedia": "http://dbpedia.org/resource/Rheumatoid_arthritis"
        },
        {
            "text": "Tumor necrosis factor-alpha",
            "yago": "http://yago-knowledge.org/resource/Tumor_necrosis_factor-alpha",
            "relevance": "0.37318",
            "freebase": "http://rdf.freebase.com/ns/m.01jyp8",
            "dbpedia": "http://dbpedia.org/resource/Tumor_necrosis_factor-alpha"
        },
        {
            "opencyc": "http://sw.opencyc.org/concept/Mx4rwP1qGpwpEbGdrcN5Y29ycA",
            "text": "Cancer",
            "relevance": "0.366447",
            "freebase": "http://rdf.freebase.com/ns/m.0qcr0",
            "dbpedia": "http://dbpedia.org/resource/Cancer"
        }
    ],
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "status": "OK",
    "url": ""
}