{
    "totalTransactions": "2",
    "url": "",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "language": "english",
    "status": "OK",
    "entities": [
        {
            "text": "Amgen Inc.",
            "sentiment": {
                "score": "0.0608422",
                "mixed": "1",
                "type": "positive"
            },
            "disambiguated": {
                "opencyc": "http://sw.opencyc.org/concept/Mx4rvitPfpwpEbGdrcN5Y29ycA",
                "dbpedia": "http://dbpedia.org/resource/Amgen",
                "freebase": "http://rdf.freebase.com/ns/m.03r820",
                "website": "http://www.amgen.com",
                "yago": "http://yago-knowledge.org/resource/Amgen",
                "crunchbase": "http://www.crunchbase.com/company/amgen",
                "name": "Amgen",
                "subType": []
            },
            "relevance": "0.952124",
            "count": "15",
            "type": "Company"
        },
        {
            "text": "Amgen",
            "sentiment": {
                "score": "-0.487069",
                "type": "negative"
            },
            "disambiguated": {
                "opencyc": "http://sw.opencyc.org/concept/Mx4rvitPfpwpEbGdrcN5Y29ycA",
                "dbpedia": "http://dbpedia.org/resource/Amgen",
                "freebase": "http://rdf.freebase.com/ns/m.03r820",
                "website": "http://www.amgen.com",
                "yago": "http://yago-knowledge.org/resource/Amgen",
                "name": "Amgen",
                "subType": [
                    "Company"
                ]
            },
            "relevance": "0.634637",
            "count": "7",
            "type": "Organization"
        },
        {
            "sentiment": {
                "score": "-0.479307",
                "type": "negative"
            },
            "text": "Amgen of marketing Aranesp",
            "relevance": "0.349249",
            "count": "1",
            "type": "JobTitle"
        },
        {
            "text": "FDA",
            "sentiment": {
                "score": "-0.240273",
                "mixed": "1",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.032mx",
                "dbpedia": "http://dbpedia.org/resource/Food_and_Drug_Administration",
                "name": "Food and Drug Administration",
                "subType": [
                    "GovernmentAgency"
                ],
                "website": "http://www.fda.gov/"
            },
            "relevance": "0.28342",
            "count": "6",
            "type": "Organization"
        },
        {
            "sentiment": {
                "score": "0.238926",
                "type": "positive"
            },
            "text": "etanercept",
            "relevance": "0.236849",
            "count": "4",
            "type": "Drug"
        },
        {
            "sentiment": {
                "score": "-0.245615",
                "type": "negative"
            },
            "text": "Xgeva",
            "relevance": "0.233277",
            "count": "3",
            "type": "Company"
        },
        {
            "text": "Swedish Orphan Biovitrum",
            "sentiment": {
                "score": "-0.412425",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.047sflh",
                "name": "Swedish Orphan Biovitrum",
                "dbpedia": "http://dbpedia.org/resource/Swedish_Orphan_Biovitrum"
            },
            "relevance": "0.221792",
            "count": "3",
            "type": "Company"
        },
        {
            "sentiment": {
                "score": "-0.545041",
                "type": "negative"
            },
            "text": "Neupogen",
            "relevance": "0.217833",
            "count": "3",
            "type": "Company"
        },
        {
            "text": "Los Angeles Times",
            "sentiment": {
                "score": "-0.372585",
                "type": "negative"
            },
            "disambiguated": {
                "opencyc": "http://sw.opencyc.org/concept/Mx4r_nr0XhlAQdiZDcR77-TkdA",
                "dbpedia": "http://dbpedia.org/resource/Los_Angeles_Times",
                "freebase": "http://rdf.freebase.com/ns/m.01p06z",
                "website": "http://www.latimes.com/",
                "yago": "http://yago-knowledge.org/resource/Los_Angeles_Times",
                "name": "Los Angeles Times",
                "subType": [
                    "AwardPresentingOrganization",
                    "AwardWinner",
                    "Newspaper"
                ]
            },
            "relevance": "0.21604",
            "count": "2",
            "type": "PrintMedia"
        },
        {
            "text": "United Kingdom",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "opencyc": "http://sw.opencyc.org/concept/Mx4rvViRhJwpEbGdrcN5Y29ycA",
                "freebase": "http://rdf.freebase.com/ns/m.07ssc",
                "dbpedia": "http://dbpedia.org/resource/United_Kingdom",
                "website": "http://www.royal.gov.uk/",
                "geo": "51.5 -0.11666666666666667",
                "yago": "http://yago-knowledge.org/resource/United_Kingdom",
                "name": "United Kingdom",
                "subType": [
                    "Location",
                    "AdministrativeDivision",
                    "GovernmentalJurisdiction",
                    "Kingdom",
                    "MeteorologicalService"
                ],
                "ciaFactbook": "http://www4.wiwiss.fu-berlin.de/factbook/resource/United_Kingdom"
            },
            "relevance": "0.201817",
            "count": "2",
            "type": "Country"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Prolia",
            "relevance": "0.200038",
            "count": "2",
            "type": "Company"
        },
        {
            "text": "Kevin W. Sharer",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.0928zs",
                "yago": "http://yago-knowledge.org/resource/Kevin_W._Sharer",
                "dbpedia": "http://dbpedia.org/resource/Kevin_W._Sharer",
                "name": "Kevin W. Sharer",
                "subType": [
                    "BoardMember",
                    "MilitaryPerson"
                ]
            },
            "relevance": "0.194605",
            "count": "2",
            "type": "Person"
        },
        {
            "sentiment": {
                "score": "0.25718",
                "type": "positive"
            },
            "text": "Dezima Pharma",
            "relevance": "0.192527",
            "count": "2",
            "type": "Company"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Conejo Valley",
            "relevance": "0.192107",
            "count": "1",
            "type": "GeographicFeature"
        },
        {
            "text": "California",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "opencyc": "http://sw.opencyc.org/concept/Mx4rvVj2upwpEbGdrcN5Y29ycA",
                "freebase": "http://rdf.freebase.com/ns/m.01n7q",
                "dbpedia": "http://dbpedia.org/resource/California",
                "website": "http://ca.gov",
                "geo": "35.458606 -119.355165",
                "yago": "http://yago-knowledge.org/resource/California",
                "name": "California",
                "subType": [
                    "Location",
                    "PoliticalDistrict",
                    "AdministrativeDivision",
                    "Appellation",
                    "GovernmentalJurisdiction",
                    "USState",
                    "WineRegion"
                ]
            },
            "relevance": "0.191337",
            "count": "1",
            "type": "StateOrCounty"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Applied Molecular Genetics",
            "relevance": "0.191105",
            "count": "2",
            "type": "PrintMedia"
        },
        {
            "text": "Thousand Oaks",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "census": "http://www.rdfabout.com/rdf/usgov/geo/us/ca/counties/ventura_county/thousand_oaks",
                "freebase": "http://rdf.freebase.com/ns/m.0r8c8",
                "dbpedia": "http://dbpedia.org/resource/Thousand_Oaks,_California",
                "website": "http://www.toaks.org/",
                "geo": "34.18944444444445 -118.875",
                "yago": "http://yago-knowledge.org/resource/Thousand_Oaks,_California",
                "geonames": "http://sws.geonames.org/5402405/",
                "name": "Thousand Oaks, California",
                "subType": []
            },
            "relevance": "0.189913",
            "count": "1",
            "type": "City"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "chief executive officer",
            "relevance": "0.188221",
            "count": "1",
            "type": "JobTitle"
        },
        {
            "text": "febrile neutropenia",
            "sentiment": {
                "score": "-0.519603",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.03h1005",
                "dbpedia": "http://dbpedia.org/resource/Febrile_neutropenia",
                "name": "Febrile neutropenia",
                "subType": [
                    "DiseaseOrMedicalCondition"
                ]
            },
            "relevance": "0.186178",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "president and chief executive officer",
            "relevance": "0.182064",
            "count": "1",
            "type": "JobTitle"
        },
        {
            "text": "George B. Rathmann",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.0jl0fp0",
                "name": "George Rathmann",
                "dbpedia": "http://dbpedia.org/resource/George_Rathmann"
            },
            "relevance": "0.181358",
            "count": "1",
            "type": "Person"
        },
        {
            "text": "prostate cancer",
            "sentiment": {
                "score": "-0.520006",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.0m32h",
                "dbpedia": "http://dbpedia.org/resource/Prostate_cancer",
                "name": "Prostate cancer",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "CauseOfDeath",
                    "RiskFactor"
                ]
            },
            "relevance": "0.17895",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "text": "immune thrombocytopenic purpura",
            "sentiment": {
                "score": "-0.642256",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.02153r",
                "dbpedia": "http://dbpedia.org/resource/Idiopathic_thrombocytopenic_purpura",
                "name": "Idiopathic thrombocytopenic purpura",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "Disease"
                ]
            },
            "relevance": "0.178191",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "score": "0.324573",
                "type": "positive"
            },
            "text": "biotechnology firm",
            "relevance": "0.174712",
            "count": "1",
            "type": "FieldTerminology"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "official",
            "relevance": "0.171261",
            "count": "1",
            "type": "JobTitle"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Robert A. Bradway",
            "relevance": "0.171209",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "co-founder",
            "relevance": "0.16963",
            "count": "1",
            "type": "JobTitle"
        },
        {
            "text": "acute lymphoblastic leukemia",
            "sentiment": {
                "score": "-0.214865",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.03fqwr",
                "dbpedia": "http://dbpedia.org/resource/Acute_lymphoblastic_leukemia",
                "name": "Acute lymphoblastic leukemia",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "Disease"
                ]
            },
            "relevance": "0.169119",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "text": "Secondary hyperparathyroidism",
            "sentiment": {
                "score": "-0.279464",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.09wb3p",
                "yago": "http://yago-knowledge.org/resource/Secondary_hyperparathyroidism",
                "dbpedia": "http://dbpedia.org/resource/Secondary_hyperparathyroidism",
                "name": "Secondary hyperparathyroidism",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "DiseaseCause",
                    "Disease"
                ]
            },
            "relevance": "0.167006",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "text": "RA",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.01n8q1j",
                "name": "Ra (American band)",
                "dbpedia": "http://dbpedia.org/resource/Ra_(American_band)"
            },
            "relevance": "0.166148",
            "count": "1",
            "type": "Organization"
        },
        {
            "text": "postmenopausal osteoporosis",
            "sentiment": {
                "score": "-0.455022",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.05mdx",
                "dbpedia": "http://dbpedia.org/resource/Osteoporosis",
                "name": "Osteoporosis",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "DiseaseCause",
                    "RiskFactor",
                    "Symptom",
                    "Disease"
                ]
            },
            "relevance": "0.16551",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "darbepoetin alfa",
            "relevance": "0.165308",
            "count": "1",
            "type": "Drug"
        },
        {
            "sentiment": {
                "score": "-0.382806",
                "type": "negative"
            },
            "text": "Sensipar",
            "relevance": "0.165189",
            "count": "1",
            "type": "City"
        },
        {
            "text": "oral mucositis",
            "sentiment": {
                "type": "neutral"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.0fqk7v",
                "yago": "http://yago-knowledge.org/resource/Mucositis",
                "dbpedia": "http://dbpedia.org/resource/Mucositis",
                "name": "Mucositis",
                "subType": [
                    "DiseaseOrMedicalCondition"
                ]
            },
            "relevance": "0.162129",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Johnson",
            "relevance": "0.161836",
            "count": "2",
            "type": "Person"
        },
        {
            "sentiment": {
                "score": "-0.425452",
                "type": "negative"
            },
            "text": "Prolia",
            "relevance": "0.160641",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Google Finance",
            "relevance": "0.160623",
            "count": "1",
            "type": "Company"
        },
        {
            "text": "spinal cord compression",
            "sentiment": {
                "score": "-0.273586",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.0cc01k",
                "yago": "http://yago-knowledge.org/resource/Spinal_cord_compression",
                "dbpedia": "http://dbpedia.org/resource/Spinal_cord_compression",
                "name": "Spinal cord compression",
                "subType": [
                    "DiseaseOrMedicalCondition",
                    "Disease"
                ]
            },
            "relevance": "0.160255",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Neulasta",
            "relevance": "0.159769",
            "count": "1",
            "type": "Person"
        },
        {
            "text": "solid tumors",
            "sentiment": {
                "score": "-0.273586",
                "type": "negative"
            },
            "disambiguated": {
                "freebase": "http://rdf.freebase.com/ns/m.07p3l",
                "dbpedia": "http://dbpedia.org/resource/Tumor",
                "name": "Tumor",
                "subType": [
                    "DiseaseCause",
                    "RiskFactor",
                    "Symptom"
                ],
                "opencyc": "http://sw.opencyc.org/concept/Mx4rwP1YqpwpEbGdrcN5Y29ycA"
            },
            "relevance": "0.159764",
            "count": "1",
            "type": "HealthCondition"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Vectibix",
            "relevance": "0.15934",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "score": "-0.231843",
                "type": "negative"
            },
            "text": "Federal prosecutors",
            "relevance": "0.15907",
            "count": "1",
            "type": "FieldTerminology"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Blinatumomab",
            "relevance": "0.159043",
            "count": "1",
            "type": "Drug"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "National Institute of Clinical Excellence",
            "relevance": "0.158851",
            "count": "1",
            "type": "Organization"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Romiplostim",
            "relevance": "0.157352",
            "count": "1",
            "type": "Drug"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Hoechst Marion Roussel",
            "relevance": "0.157213",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Gordon M. Binder",
            "relevance": "0.157105",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "type": "neutral"
            },
            "text": "Cinacalcet",
            "relevance": "0.156729",
            "count": "1",
            "type": "Drug"
        },
        {
            "sentiment": {
                "score": "-0.304764",
                "type": "negative"
            },
            "text": "Xencor",
            "relevance": "0.156676",
            "count": "1",
            "type": "Person"
        },
        {
            "sentiment": {
                "score": "-0.570479",
                "type": "negative"
            },
            "text": "immune systems",
            "relevance": "0.156544",
            "count": "1",
            "type": "FieldTerminology"
        }
    ]
}