{
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "status": "OK",
    "url": "https://en.wikipedia.org/wiki/Amgen",
    "feeds": []
}