{
    "language": "english",
    "taxonomy": [
        {
            "label": "/health and fitness/disease/cancer",
            "score": "0.490817"
        },
        {
            "label": "/health and fitness/disease",
            "score": "0.457881"
        },
        {
            "label": "/news",
            "score": "0.434213"
        }
    ],
    "totalTransactions": "1",
    "usage": "By accessing AlchemyAPI or using information generated by AlchemyAPI, you are agreeing to be bound by the AlchemyAPI Terms of Use: http://www.alchemyapi.com/company/terms.html",
    "status": "OK"
}